version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: mindforge-server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=mindforge
      - DB_PASSWORD=mindforge_password
      - DB_NAME=mindforge
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: mysql:8.0
    container_name: mindforge-db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mindforge
      - MYSQL_USER=mindforge
      - MYSQL_PASSWORD=mindforge_password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: